### PR TITLE
Add index.d.ts for Typescript.

### PR DESCRIPTION
**Pull request by xuwaters**
I've added a Typescript definition file for this great library.
Please correct me if I made something wrong, thanks :)

### CODE REVIEW

**Comment by zxf4399** [comment]
merge ?

**Comment by tyler-ground** [comment]
Any reason why this isn't merged yet?

**Comment by Simon-Hivehub** [comment]
What's up with that merge?

**Comment by tyler-ground** [comment]
@Simon-Hivehub No commits since March... project is dead.

**Comment by justinanastos** [comment]
@xuwaters thanks for this! Since this project appears abandoned; maybe submit to definitely typed?

**Comment by Sunnyjson** [comment]
Does anyone know how to run TypeScript now

**Comment by prateek332** [comment]
There are few props missing for certain components in this library, like `order` prop for components that goes inside `ControlBar ` component.
But after fixing them all, this commit should definitely be merged 😠. @xuwaters did an incredible job creating types for this video player library. Please consider this request 🙏 @JimLiu @mondaychen

**Pull request merged**
