### PR TITLE
Move default prop from Video to Player

### LINKED ISSUE #229: preload="auto" is not overwritable
**Describe the bug**
When I set preload="none" it is on auto.

```
    <Player
        playsInline
        preload="none"
    >
        <source src={video.file.url} type="video/mp4" />
        <BigPlayButton position="center" />
    </Player>
```

**Expected behavior**
preload should be set to none.

**Additional context**
Is this an usage error or a bug?

### PR DESCRIPTION
**Pull request by mondaychen**
This will fix #229

### CODE REVIEW

**Comment by mondaychen** [comment]
@JimLiu I'm thinking about the relationship between Player and Video -- in our docs, Video is never mentioned. It seems that anything you want to do on Video, you can do it on Player instead. Maybe we should stop exporting `<Video>` to users?

The only use case I can think of is that you when you need a class name on Video, you can't put it on Player (because that class name will apply to the `div` wrapper)

**Comment by xiaoyuhen** [comment]
LGTM

**Comment by mondaychen** [comment]
I merged so that we can do the release for bugfix, but let's continue the discussion about Video component here

**Comment by mondaychen** [comment]
Also, I realized that in #192 there's a behavior change: if a default child of `Player` or `ControlBar` has default props, before 192 it will be overwritten by the same prop in the parent element (via `{...props}`), after 192 it will not.

The being said, other than the `<Video>` and `<Player>` case I don't foresee many use cases, so it's not a big deal for now. But it's still something to consider.

**Pull request merged**
